title: CLIJ
logo: /images/clij_logo.png
description: GLIJ: GPU-accelerated image processing in Fiji
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-redirect-from
