title: CLIJ
logo: /images/clij_logo.png
description: GPU-accelerated image processing in ImageJ using CLIJ
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-redirect-from
